DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Trade;
DROP TABLE IF EXISTS Stock;
DROP TABLE IF EXISTS Followers;
DROP TABLE IF EXISTS Users;
